### ISSUE TITLE
Consider reverting the following

### ISSUE THREAD

**Issue by asiimwedismas** [ayu-theme/vscode-ayu#101]
1. "selection.background": "#273747"
The selection background in the Find input (Ctrl F) doesn't show with this new setting, consider changing it back to #273747fd
![slection](https://user-images.githubusercontent.com/51087315/84811587-c4285200-b015-11ea-9bbd-f11aea7b451b.png)

2. "descriptionForeground": "#ff3333"
Red and orange don't go well together on the welcome page. Also, consider reverting it to the original grey
![red, orange](https://user-images.githubusercontent.com/51087315/84811558-b672cc80-b015-11ea-90dd-431716a88c19.png)

**Comment by dempfi** [comment]
@asiimwedismas oh my, thank you for reporting

**Comment by dempfi** [comment]
Published a fix

**Comment by asiimwedismas** [comment]
Great, was just about to create a pull request for it. Otherwise, great theme

**Comment by dempfi** [comment]
You can still create a pull request with other improvements 😉
