### ISSUE TITLE
Icon for ipynb

### ISSUE THREAD

**Issue by parthe** [ayu-theme/vscode-ayu#104]
Now that VSCode has support for editing .ipynb files (Jupyter notebooks)
I think the .ipynb format deserves a font of its own

**Comment by dempfi** [comment]
Great point, thank you @parthe. I’ll look into that.

**Comment by laurencedeclan** [comment]
Just commenting to say that this is an amazing theme for Python and it would be even better if Jupyter notebooks didn't show up with a placeholder icon.

**Comment by dempfi** [comment]
Fixed in the latest release
