### ISSUE TITLE
Incorrect Highlighting for functions within ``-strings in JavaScript

### ISSUE THREAD

**Issue by EriKWDev** [ayu-theme/vscode-ayu#106]
I seem to have discovered an edge-case where \`\`-strings in JavaScript aren't highlighted correctly using the Ayu theme. As you can see in the images bellow, the `({})`:s of the object defined within the evaluated function within the ``-string gets highlighted incorrectly.

## Built-in theme
![image](https://user-images.githubusercontent.com/19771356/89630794-20825200-d8a0-11ea-8d07-8a7c87e6eaec.png)

### Ayu Dark
![image](https://user-images.githubusercontent.com/19771356/89630465-b49fe980-d89f-11ea-9077-3e6a63e646de.png)

### Ayu Light
![image](https://user-images.githubusercontent.com/19771356/89630582-e1540100-d89f-11ea-8ef2-7bb6b3cdd64b.png)

## Code to reproduce:
In a javascript file (.js), paste the following:
```JavaScript
let value = `${JSON.stringify({ "incorrect": "highlighting" })}`
let expected = JSON.stringify({ "correct": "highlighting" })
```
*(Github's built-in highlighting here highlights it correctly as well)

**Comment by dempfi** [comment]
Thx for reporting @EriKWDev. Fixed in v1, also improved a bit on the punctuation around string literals
