### ISSUE TITLE
Consider providing extension in open-vsx.org

### ISSUE THREAD

**Issue by douglasrizzo** [ayu-theme/vscode-ayu#108]
http://open-vsx.org is an open registry for extensions targeted towards VSCode-compatible editors, such as VSCodium, the open, MIT-licensed version of VSCode. People who use this open version of VSCode cannot install this extension and providing it on open-vsx would solve that. Thank you.

**Comment by meduzen** [comment]
Is there a workaround to install it in the meantime?

**Comment by douglasrizzo** [comment]
Yes, it is described here (for VSCodium): https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace

**Comment by meduzen** [comment]
Someone made it available for Codium a month or so, and it’s working well. 👍

**Comment by douglasrizzo** [comment]
Great!

**Comment by jonghwanhyeon** [comment]
Please consider updating the extension on the Open VSX Registry. There are many VS Code compatible editors like Antigravity or Cursor that rely on it, but the current version of [the ayu theme in Open VSX](https://open-vsx.org/extension/teabyii/ayu) is outdated by about 3 months. An update would be greatly appreciated!

**Comment by dempfi** [comment]
@jonghwanhyeon ayu is in the autopublish queue already and from what I see got a proper version bump following the release in vscode marketplace
