### ISSUE TITLE
Hover in status bar in debug mode makes text unreadable

### ISSUE THREAD

**Issue by avborup** [ayu-theme/vscode-ayu#120]
The status bar when debugging becomes red:

![image](https://user-images.githubusercontent.com/16561050/125409700-7454bf80-e3bc-11eb-81e8-0ec79e4c65e9.png)

Hovering over a field makes it dark:

![image](https://user-images.githubusercontent.com/16561050/125409779-8a628000-e3bc-11eb-8ed0-090613dee3c8.png)

The hover background color is the same as when you are not debugging - but when you are not debugging, the text is white/grey, not black:

![image](https://user-images.githubusercontent.com/16561050/125410001-bc73e200-e3bc-11eb-977a-de545416d267.png)

**Comment by dempfi** [comment]
Fixed in v1
