### ISSUE TITLE
different color between HTML tags and Component tags

### ISSUE THREAD

**Issue by quanscheng** [ayu-theme/vscode-ayu#121]
when use VUE or REACT
eg: 
the color of  `<Component>` is the same as the `<div>` .... 

wish the colors of the two labels can be distinguished
thanks, ayu is very beautiful theme , and wish it's to be better.

**Comment by leutzed** [comment]
oh boy i want it so badly

up up up

**Comment by meduzen** [comment]
Do you have examples of themes making this useful and nice?

**Comment by leutzed** [comment]
the themes that i like that have this features are the Github Theme, Dracula and Omni Theme. I also tried to modify ayu based on the variables that those themes provide, but no sucess :(

**Comment by leutzed** [comment]
yo guys, found a way to do this in your user settings

Ctrl + Shift + P > Open Settings (JSON) > paste this code, changing the "foreground" color with one of your preference.

`"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                 "entity.name.tag.tsx", 
                 ],
                 "settings": {
                 "foreground": "#569CD6",
                 }
            },
        ]
    }`

**Comment by dempfi** [comment]
Great suggestion @quanscheng. I'll adopt @leutzed's suggested solution into the next release

**Comment by leutzed** [comment]
sure, but @dempfi use a color which is in the ayu-colors repo, than you won't need to change the pallete :)

**Comment by dempfi** [comment]
Released in v1
