### ISSUE TITLE
Highlighted Code is hard to Notice

### ISSUE THREAD

**Issue by taufiqahmed** [ayu-theme/vscode-ayu#22]
When you highlight a code and wants to find duplicate by scrolling, it's very difficult to distinguish in colors.

**Comment by teabyii** [comment]
Which theme? Light, Dark or Mirage? Please put the screenshot here? Thanks.

**Comment by taufiqahmed** [comment]
Sorry for late. Here are the screenshots using all three color theme. I've selected 'function' and see how other instance of function string are hard to notice. 

![auymirage](https://user-images.githubusercontent.com/8788600/28630388-f70ba704-724b-11e7-88f2-ae7f5307be9c.PNG)
![ayudark](https://user-images.githubusercontent.com/8788600/28630386-f6fb78ca-724b-11e7-8fed-adc4f9925f94.PNG)
![ayulight](https://user-images.githubusercontent.com/8788600/28630387-f6fcead4-724b-11e7-954f-5a1c3a0d843b.PNG)

**Comment by imoby** [comment]
I definitely second this! I use the mirage theme and when I search or do multiple cursors within a file, it is very difficult to see what is highlighted

**Comment by dempfi** [comment]
@taufiqahmed latest release introduced some improvements in this area. Can you check and give feedback?

**Comment by taufiqahmed** [comment]
Thanks, I will check it out.

On Aug 16, 2018 2:36 PM, "Ike Ku" <notifications@github.com> wrote:

@taufiqahmed <https://github.com/taufiqahmed> latest release introduced
some improvements in this area. Can you check and give feedback?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/teabyii/vscode-ayu/issues/22#issuecomment-413469297>,
or mute the thread

**Comment by alexsasharegan** [comment]
I'll plus one this as a big dark theme user. Here's my example I had posted to a different issue thread:

Here's an example with *Ayu Dark* where I have `hits` selected. The selection and the usage below are dim, while above is bright and what I would prefer consistently.

![image](https://user-images.githubusercontent.com/16269252/44362850-2abea200-a477-11e8-8d19-be7a28d15d55.png)

**Comment by aengl** [comment]
I'd agree that this is still my biggest issue with the theme. I've been using it with this customisation for a long time now:

```
"workbench.colorCustomizations": {
  "[Ayu Dark]": {
    "editor.wordHighlightBorder": "#a0a0a0",
    "editor.wordHighlightStrongBorder": "#ffffff",
    "editorBracketMatch.border": "#a0a0a0"
  }
}
```

Not that I'm suggesting that this is a good solution, but it's a good enough workaround for me.

There definitely have been some noticeable improvements recently, though. Especially the added borders for find matches really help. Thank you for your work on this extension ❤️

**Comment by alexsasharegan** [comment]
Agreed, those borders are both visually helpful and good looking.

**Comment by taufiqahmed** [comment]
The latest release 0.15.0 has fixed the issue. Now the highlights are more prominent. 
Here is the screenshot of my favourite Ayu Mirage:

![image](https://user-images.githubusercontent.com/8788600/44829657-aa9af800-ac3f-11e8-95b6-ca1bc8b348d8.png)

Thanks a lot.

**Comment by dempfi** [comment]
Hey guys, closing this issue. Seems like we've addressed most of the problems. If you feel otherwise please don't hesitate to reopen or submit new one :)
