### ISSUE TITLE
Dim gitignored folders/files

### ISSUE THREAD

**Issue by jwhitmarsh** [ayu-theme/vscode-ayu#47]
It would be nice if folders & files that are gitignored were faded out/dimmer than included ones. It looks like this is achievable https://github.com/Microsoft/vscode/issues/178#issuecomment-335511695

**Comment by jwhitmarsh** [comment]
FYI for anyone coming to this, in Code v1.20.1 you can overwrite/add to theme colors in your preferences:

`
    "workbench.colorCustomizations": {
        "gitDecoration.ignoredResourceForeground": "#b9bbbd"
    }
`

**Comment by dempfi** [comment]
Fixed in #60.
