### ISSUE TITLE
Contrast is very low

### ISSUE THREAD

**Issue by Loreno10** [ayu-theme/vscode-ayu#66]
Hello,
I just installed Ayu and I noticed that actual theme looks a bit different than the screenshots shown in Extensions of VS Code.
Here's my screen:
![zrzut ekranu 2018-09-29 o 11 30 59](https://user-images.githubusercontent.com/10273406/46244207-a8ad8b80-c3db-11e8-8074-d4fd2e597538.png)

FOr exmaple, look at the icons on the left-panel of VS Code. They are barely visible, while on the extension's official screenshots they have better contrast.
Is something wrong wit my setup? I tried reinstalling the extension, but nothing changed.

**Comment by edwardloveall** [comment]
@Loreno10 I've had this same issue. Thanks for reporting it. Unless we both have bad setups, it seems like the screenshots are definitely a mismatch. If I had to guess, I think it would be this PR that changed it: https://github.com/teabyii/vscode-ayu/pull/60

**Comment by Loreno10** [comment]
@edwardloveall Yes, I think you're right. Honestly I don't know how they accepted this into main branch. I understand that editor should focus on the code the most, but right now it's done not right. I hope it'll be changed.

**Comment by edwardloveall** [comment]
Another thing that I just thought of is that macOS Mojave disables font smoothing (subpixel antialiasing). I recently upgraded to it and it's making a lot of fonts harder to read. I just disabled it and here's what my theme looks like now:

![screenshot of the Ayu dark theme in VSCode](https://user-images.githubusercontent.com/49549/46265934-23b89400-c4f9-11e8-940e-e39c666ba5f6.png)

Much more readable in my opinion.

You could try changing that setting (and logging out/in) to see if it makes a difference:

```sh
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

**Comment by edwardloveall** [comment]
It's certainly better for me! Thanks for the updates!

**Comment by kinghat** [comment]
maybe its just me but i feel like the side bar icons, explorer file name text, window tab text and the breadcrumb texts are hard to see. basically all the text non editor text. my monitors probably arent helping either:

![image](https://user-images.githubusercontent.com/16073360/66769415-b7e26880-ee7a-11e9-8b4c-ad02435da0a3.png)

**Comment by tamj0rd2** [comment]
I also have some problems with the contrast to the point where I can't use the theme anymore. I might fork it and play around with it for a bit.

**Comment by thomasbrus** [comment]
You can override the theme colors in `settings.json` like below. Should be a lot better already 👍 

```json
  "workbench.colorCustomizations": {
    "[Ayu Mirage]": {
      "dropdown.foreground": "#a1acc0",
      "foreground": "#a1acc0",
      "list.inactiveSelectionForeground": "#a1acc0",
      "panelTitle.inactiveForeground": "#a1acc0",
      "peekViewResult.fileForeground": "#a1acc0",
      "peekViewTitleDescription.foreground": "#a1acc0",
      "peekViewTitleLabel.foreground": "#a1acc0",
      "sideBarSectionHeader.foreground": "#a1acc0",
      "statusBar.foreground": "#a1acc0",
      "tab.inactiveForeground": "#a1acc0",
      "tab.unfocusedActiveBorder": "#a1acc0",
      "tab.unfocusedActiveForeground": "#a1acc0",
      "tab.unfocusedInactiveForeground": "#a1acc0",
      "titleBar.inactiveForeground": "#a1acc0",
      "activityBar.foreground": "#a1acc0",
      "list.focusBackground": "#000",
      "list.hoverBackground": "#000",
      "list.activeSelectionBackground": "#000",
      "editorSuggestWidget.selectedBackground": "#000",
      "selection.background": "#a1acc0",
    }
  },
```

**Comment by tamj0rd2** [comment]
Thanks, that's a huge improvement! I've also added this line for git ignored files:
```json
"gitDecoration.ignoredResourceForeground": "#5d6370"
```

**Comment by eduardocanellas** [comment]
Hello! I agree about the contrast, especially on Ayu Dark. Currently, the text which is not inside the editor is a bit hard to read. I made some color customizations (as suggested above) and it's really nice now. In my case, the color 586173 worked very well.

**Comment by dempfi** [comment]
Another bunch of updates to contrast landed in v1. Hope you like it guys
