### ISSUE TITLE
Light Theme: White Terminal Color unreadable

### ISSUE THREAD

**Issue by ccaspers** [ayu-theme/vscode-ayu#68]
When using the light theme, the terminal's white color should be rendered as grey/black. In its current form, certain outputs are unreadable. I attached some screenshots to show what I mean:

- Ayu Light
![terminal-ayu-light](https://user-images.githubusercontent.com/2117023/47571430-cd444700-d938-11e8-9c07-fa571aabc221.png)
- Light (Visual Studio)
![terminal-vscode-default](https://user-images.githubusercontent.com/2117023/47571432-cddcdd80-d938-11e8-9bbb-948dec34af20.png)

**Comment by ccaspers** [comment]
Fixed it in https://github.com/teabyii/vscode-ayu/pull/69

**Comment by dempfi** [comment]
Hi @ccaspers, could you check please if the latest fixes the issue for you. If not, let's see if we can push your PR :)

P.S. Sorry for the delay in response — I accidentally turned notifications off for the repo :/

**Comment by ccaspers** [comment]
@dempfi no problem, glad you saw it anyway :) I updated my pull request. The issue remained after the latest update as brightWhite for the light variant still was at #FFFFFF. I chose #D1D1D1 rather arbitrarily. If the original ayu colors provide a grey with a similar brightness, we should probably choose that instead.

**Comment by dempfi** [comment]
Merged. @ccaspers Thank you very much for your contribution 🙏
