### ISSUE TITLE
PDF Icon Not Working

### ISSUE THREAD

**Issue by Astrantia** [ayu-theme/vscode-ayu#71]
![image](https://user-images.githubusercontent.com/32885386/49004051-62518000-f131-11e8-8c07-bd7e39a2b9da.png)
is shown for pdfs. Is this supposed to be so?

**Comment by teabyii** [comment]
There is no icon for pdf file now, sorry.

**Comment by Astrantia** [comment]
@teabyii https://github.com/teabyii/vscode-ayu/blob/master/icons/file_type_pdf%402x.png what is this then?

**Comment by teabyii** [comment]
Sorry, I miss it. I will fix it soon.

**Comment by muhammadridho** [comment]
I've just pull requested for this issue 
https://github.com/ayu-theme/vscode-ayu/pull/80

**Comment by muhammadridho** [comment]
> Sorry, I miss it. I will fix it soon.

I've just pull requested for this issue 
https://github.com/ayu-theme/vscode-ayu/pull/80
