### ISSUE TITLE
Make items in navigation tree stand out more in dark 

### ISSUE THREAD

**Issue by Astrantia** [ayu-theme/vscode-ayu#72]
![image](https://user-images.githubusercontent.com/32885386/49199449-dffdd180-f365-11e8-83cf-6f0ab124fe5a.png)

The items in the explorer are barely visible. Color is fine but it's way too dark. Can brightness be increased somehow?

Compare the grey text from terminal:
![image](https://user-images.githubusercontent.com/32885386/49199496-091e6200-f366-11e8-85f3-70875d779e6a.png)

to the grey text in explorer:
![image](https://user-images.githubusercontent.com/32885386/49199499-0facd980-f366-11e8-87ee-b2b4b785a3dd.png)

**Comment by Astrantia** [comment]
@teabyii this is especially an issue in ayu dark. Text cant be seen at all

**Comment by dempfi** [comment]
@Astrantia that was the intention behind the dark theme — focused coding (contrast editor) during deep night with all lights off. Mirage is better suited for comfortable work with lights on. 

However, I would really appreciate if you could describe your workflow and what aspects of the dark theme are the most appealing to you so we could improve it and overall experience.

**Comment by kleinfreund** [comment]
There is a big difference between avoiding distraction and making things illegible. I’d very much like this color scheme to feature a significantly increased contrast for all UI parts that are not an editor.

**Comment by kleinfreund** [comment]
@dempfi As this is the scope of this issue, I’m talking about the dark theme in particular. Also, the low contrast is most obvious in the dark theme. The other variants have slightly better contrast because they’re lighter in general.

**Comment by dempfi** [comment]
@kleinfreund I see, in what environment do you use the dark theme? Daylight/dim lights/no lights?

**Comment by kleinfreund** [comment]
@dempfi I just installed the theme so I don’t have much experience with this particular theme in my common environments.

Usually, I work during the day in a regulalry-lit room. If it’s dark outside, I have lights on. Considering what you stated earlier about the intention of the dark theme, I’m very much not the target audience. 
So increasing the contrast for the dark theme might not be in the interest of some of its users. A higher contrast variant of the theme would work, but that would also be quite tedious to maintain, especially considering that Ayu already has quite a few variants.

**Comment by AlexDemzz** [comment]
Use this https://marketplace.visualstudio.com/items?itemName=allmeta.ayu-dark-meta

**Comment by rilex037** [comment]
this theme would be perfect only if this items are a bit brighter, even more so cause i dim my screen while i'm coding in dark
![image](https://user-images.githubusercontent.com/44920715/84717523-54af5580-af76-11ea-91a4-ad484e323fe5.png)

**Comment by asiimwedismas** [comment]
@rilex037   head over to settings .json > add the "blow" in the file

"workbench.colorCustomizations": {
 #This is where you change the few aspects of the theme you don't like. Otherwise, I doubt it would be possible to make the theme to every user's liking. happy coding mate 😃 
}

**Comment by dempfi** [comment]
Guys, I did quite a lot of contrast related changes for dark theme in the recent release. What's you opinion on those?

@rilex037, I don't have that context menu (I see native OS menu) to test it. I'll see what I can do to repro. For now, @asiimwedismas advice is a good place to start.

**Comment by rilex037** [comment]
@asiimwedismas thanks, I did some customization and it looks my better, just couldn't find the values for selected items, whenever i select something, it looks same as disabled. 

![image](https://user-images.githubusercontent.com/44920715/85102985-14fe9d00-b206-11ea-947e-75b4cca64bdc.png)

**Comment by rilex037** [comment]
sorry, found it 
```
      "list.activeSelectionForeground": "#ffcc66",
      "list.hoverForeground": "#fff",
```

**Comment by dempfi** [comment]
I've applied a bunch of updates to these in v1. Give it a shot 😉
