### ISSUE TITLE
[Question] Font used in README header image

### ISSUE THREAD

**Issue by dohyeunglee** [ayu-theme/vscode-ayu#73]
Can anyone let me know the font name used in README header image(screenshot)? 

I searched previous issues in this repo and other ayu repo but I only found "Operator mono" and 

"Roboto Mono" which are not correct. Someone says it's Pragmata pro. is it correct?

**Comment by srid** [comment]
There is no answer to this question yet. See also https://github.com/ayu-theme/vscode-ayu/issues/48

**Comment by dempfi** [comment]
@dohyeunglee hey, those who say PragamataPro are correct. I use PragamataPro and took the screenshots with it.
