### ISSUE TITLE
Add Webpack icon

### ISSUE THREAD

**Issue by Gaspacchio** [ayu-theme/vscode-ayu#75]
I just noticed that the Webpack icon is not shown when creating a webpack config file. It would be nice if it could be added to this already beautiful icon pack. The file name is `webpack.config.js`.

I don't reallly know if this is the place to request a new icon but I thought why not trying?

**Comment by Nuc1eoN** [comment]
Same for [Rollup](https://rollupjs.org/guide/en/) and it's corresponding `rollup.config.js` actually :)
