### ISSUE TITLE
Focus and mouse over should have different colors (eg. in palette)

### ISSUE THREAD

**Issue by nicolas-cherel** [ayu-theme/vscode-ayu#78]
| Ayu | VS theme |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/208296/54837354-6d26b680-4cc6-11e9-97e7-c9ad952d30d8.png) | ![image](https://user-images.githubusercontent.com/208296/54837395-8f203900-4cc6-11e9-8614-4ba592d8f190.png) |
| palette show no difference between mouse over and focused element | vs code theme shows colors for focused element |

**Comment by dempfi** [comment]
Fixed in v1
