### ISSUE TITLE
JavaScript Template Literal Highlighting

### ISSUE THREAD

**Issue by zackkrida** [ayu-theme/vscode-ayu#82]
Love the theme and it looks great! Quick feedback, when writing template literals in javascript, like so:

```js
const name = `Zack`
const hello = `Hello, my name is ${name}`
```

Most themes make the "${" and "}" a distinct color so that it's obvious that they're not being output in the string. Here's a comparison to the 'Horizon" theme:

<img width="859" alt="Screenshot 2019-06-15 12 38 27" src="https://user-images.githubusercontent.com/6351754/59553979-da1ab700-8f6a-11e9-8ff3-b3520544ad10.png">
<img width="839" alt="Screenshot 2019-06-15 12 38 37" src="https://user-images.githubusercontent.com/6351754/59553980-da1ab700-8f6a-11e9-9037-3e7aa01602ce.png">

**Comment by gl00m3r** [comment]
Hello.
You can fix it easily. I did it for myself.
```javascript
"editor.tokenColorCustomizations": {
	"[Ayu Mirage]": { // theme name
		"textMateRules": [
			{
				"scope":["punctuation.definition.template-expression"],
				"settings": {
				"foreground": "#ffa759" // color
			}
		}
	}
}
```
Just add this code for your _settings.json_.

**Comment by dempfi** [comment]
Fixed in v1
