### ISSUE TITLE
possibility for Visual Studio 2019

### ISSUE THREAD

**Issue by akrsnr** [ayu-theme/vscode-ayu#90]
Would you mind adapting the ayu themes to VS2019?

**Comment by dempfi** [comment]
Hi @akrsnr, I'm sure what that entails — the amount of work, what kind of work, etc. If it's automated, I think it should be possible. However, AFAIK, VS is still windows only and I don't have windows machine to test it.

**Comment by dempfi** [comment]
Here you go https://marketplace.visualstudio.com/items?itemName=dempfi.ayu-vs
