### ISSUE TITLE
Highlight color is barely visible

### ISSUE THREAD

**Issue by danechitoaie** [ayu-theme/vscode-ayu#96]
Hi, this theme is awesome so thank you and good job!
But I have a problem on Ayu Miraje Bordered with the color used to highlight the text when it's selected. It's barely visible and I have trouble seeing what's selected and what not.
Here's an example bellow: (asds is selected, while the last two ss are not
<img width="621" alt="Screenshot 2020-05-19 at 17 28 28" src="https://user-images.githubusercontent.com/10779010/82339311-8fb17e00-99f6-11ea-87b7-2f99fb822b03.png">

**Comment by dempfi** [comment]
Hi @danechitoaie, this was addressed in the recent release. How do you like it?

**Comment by danechitoaie** [comment]
Awesome. Thank you.
